"""add password text column to account table

Revision ID: 197cf580de7c
Revises: 4745bc6245d9
Create Date: 2025-03-31 13:48:30.930621

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "197cf580de7c"
down_revision: str | None = "4745bc6245d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts", sa.Column("password_hash_text", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "password_hash_text")
    # ### end Alembic commands ###
